### ISSUE TITLE
Improve tooltip information 

### ISSUE THREAD

**Issue by Tamarer** [Fernando-Fernandez/SalesforceFlowExtension#1]
Thank you for creating this great extension, it is very useful for people like me who review flows all day. Some suggestions for improvements
1. Tooltip for calling a sub flow should show the variable names, currently it is shown undefined 
2.  Tooltips for create and update components should show more information about the options selected, currently it is not showing much information.

Overall this is a great idea and I use it every day. Thank you for giving this tool to the community.

**Comment by Fernando-Fernandez** [comment]
Hi @Tamarer !

I've released version 1.1.1 of the flow with a few improvements and you should see more information about sub flows.

https://chrome.google.com/webstore/detail/salesforce-flow-extension/dpeebajhbigfamnhmnlabecogegimodb/related
