### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by waynechungvs** [Fernando-Fernandez/SalesforceFlowExtension#2]
I use an api key under an org that still with 120 USD this month, which should not exceed the limit, but I still received this from the response: OpenAI: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors. (insufficient_quota)   

![image](https://github.com/Fernando-Fernandez/SalesforceFlowExtension/assets/105181305/42387528-c777-4d55-9ca9-2caaa41f7e71)

**Comment by Fernando-Fernandez** [comment]
![image](https://github.com/Fernando-Fernandez/SalesforceFlowExtension/assets/19373920/9c33397f-fb6b-445a-a7e6-a40cb6fb3f52)

You have to ask OpenAI about this.
That image is showing that you had a credit of $18 but it expired on April 1st 2023, so you ran out of credits. It has nothing to do with the limit, the credit is the issue.

They're not going to let you use their API if you have $0 credits.

The link you pasted says:  "429 - You exceeded your current quota, please check your plan and billing details	Cause: You have **run out of credits** or hit your maximum monthly spend.
Solution: **Buy more credits** or learn how to increase your limits"
